language: python
before_install:
 - node --version
install: make env node_modules
before_script:
 - psql -U postgres -c 'CREATE DATABASE "gittip-test";'
script: make test jstest
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#gittip"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
